#!/usr/bin/env python3
"""Generates tests/fixtures/*.json by pure computation.

STATUS: NEVER COMPILED / NEVER RUN AGAINST math.rs — this script is an
independent re-implementation of math.rs's formulas in plain Python
(standard library only, no third-party packages, so it needed no network
access this environment doesn't have). It exists so the numbers in the
*.json files have a computed, checkable provenance instead of being typed
by hand, and so that once a toolchain exists, `cargo test` output for
math.rs can be diffed against these vectors as two independent
implementations of the same formulas. It has not itself been executed
against a Rust build — it was run standalone with plain `python3` to
produce the committed JSON.

Re-run with: python3 tests/fixtures/generate_fixtures.py
"""

import json
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

CONDITION_GREATER_THAN = 0
CONDITION_LESS_THAN = 1
OUTCOME_NO = 0
OUTCOME_YES = 1


def truncating_div(a: int, b: int) -> int:
    """Integer division truncating toward zero, matching Rust's `/` on
    signed integers (as opposed to Python's `//`, which floors toward
    negative infinity). All values used in these fixtures are
    non-negative, where truncation and flooring coincide, but this helper
    keeps the generator correct in general rather than by accident."""
    q = abs(a) // abs(b)
    if (a < 0) != (b < 0):
        q = -q
    return q


def normalize_to_e8(value: int, exponent: int) -> int:
    """Mirrors math.rs::normalize_to_e8 exactly: shift = exponent + 8;
    multiply by 10**shift if shift >= 0, else truncating-divide by
    10**(-shift)."""
    shift = exponent + 8
    if shift >= 0:
        return value * (10**shift)
    return truncating_div(value, 10 ** (-shift))


def resolve_confidence_band(condition: int, price_e8: int, conf_e8: int, threshold_e8: int):
    """Mirrors math.rs::resolve_confidence_band exactly. Returns
    OUTCOME_YES, OUTCOME_NO, or None (AMBIGUOUS)."""
    lower = price_e8 - conf_e8
    upper = price_e8 + conf_e8
    if condition == CONDITION_GREATER_THAN:
        if lower > threshold_e8:
            return OUTCOME_YES
        if upper <= threshold_e8:
            return OUTCOME_NO
        return None
    if condition == CONDITION_LESS_THAN:
        if upper < threshold_e8:
            return OUTCOME_YES
        if lower >= threshold_e8:
            return OUTCOME_NO
        return None
    raise ValueError("invalid condition")


def pro_rata_share(payout_pool: int, share_stake: int, total_stake: int) -> int:
    """Mirrors math.rs::pro_rata_share exactly: floor(payout_pool *
    share_stake / total_stake) via integer (u128-equivalent) arithmetic."""
    return (payout_pool * share_stake) // total_stake


# ---------------------------------------------------------------------------
# normalization.json — exponent -6, -8, -9; identity, scale-up, scale-down,
# non-exact division (floor behavior), and zero.
# ---------------------------------------------------------------------------

def build_normalization_fixture():
    cases = []

    def add(name, value, exponent):
        cases.append(
            {
                "name": name,
                "value": value,
                "exponent": exponent,
                "shift": exponent + 8,
                "expected_e8": normalize_to_e8(value, exponent),
            }
        )

    # exponent = -8 -> shift = 0 -> identity
    add("exp_-8_identity_typical_price", 123_456_789, -8)
    add("exp_-8_identity_zero", 0, -8)
    add("exp_-8_identity_one", 1, -8)

    # exponent = -6 -> shift = 2 -> multiply by 100
    add("exp_-6_scale_up_typical_price", 150_00, -6)
    add("exp_-6_scale_up_large", 999_999_999, -6)
    add("exp_-6_scale_up_zero", 0, -6)

    # exponent = -9 -> shift = -1 -> divide by 10, floor (all positive here)
    add("exp_-9_scale_down_exact", 1_234_567_890, -9)
    add("exp_-9_scale_down_inexact_floors", 1_234_567_895, -9)  # 895/10 -> floors to 89
    add("exp_-9_scale_down_below_ten_floors_to_zero", 9, -9)

    # extra boundary-flavored exponents
    add("exp_0_scale_up_by_1e8", 5, 0)
    add("exp_-12_scale_down_by_1e4", 123_456_789_012, -12)

    return {
        "description": (
            "normalize_to_e8(value, exponent): shift = exponent + 8; "
            "multiply by 10**shift if shift >= 0, else truncating-divide "
            "by 10**(-shift). Generated by generate_fixtures.py, an "
            "independent Python re-implementation of math.rs::normalize_to_e8."
        ),
        "cases": cases,
    }


# ---------------------------------------------------------------------------
# confidence_band.json — GREATER_THAN and LESS_THAN, YES/NO/AMBIGUOUS,
# including the exact boundary cases where price ± conf == threshold.
# ---------------------------------------------------------------------------

def build_confidence_band_fixture():
    cases = []

    def add(name, condition, price_e8, conf_e8, threshold_e8):
        outcome = resolve_confidence_band(condition, price_e8, conf_e8, threshold_e8)
        cases.append(
            {
                "name": name,
                "condition": condition,
                "price_e8": price_e8,
                "conf_e8": conf_e8,
                "threshold_e8": threshold_e8,
                "lower": price_e8 - conf_e8,
                "upper": price_e8 + conf_e8,
                # null == AMBIGUOUS, matching Rust's Option<u8> == None
                "expected_outcome": outcome,
            }
        )

    # GREATER_THAN
    add("gt_yes_strictly_above_band", CONDITION_GREATER_THAN, 110, 5, 100)
    add("gt_no_upper_boundary_inclusive", CONDITION_GREATER_THAN, 95, 5, 100)
    add("gt_ambiguous_band_straddles_threshold", CONDITION_GREATER_THAN, 100, 5, 100)
    add("gt_ambiguous_lower_exactly_equals_threshold", CONDITION_GREATER_THAN, 105, 5, 100)
    add("gt_no_upper_exactly_equals_threshold_zero_conf", CONDITION_GREATER_THAN, 100, 0, 100)
    add("gt_yes_zero_conf_strictly_above", CONDITION_GREATER_THAN, 101, 0, 100)

    # LESS_THAN (mirror image)
    add("lt_yes_strictly_below_band", CONDITION_LESS_THAN, 90, 5, 100)
    add("lt_no_lower_boundary_inclusive", CONDITION_LESS_THAN, 105, 5, 100)
    add("lt_ambiguous_band_straddles_threshold", CONDITION_LESS_THAN, 100, 5, 100)
    add("lt_ambiguous_upper_exactly_equals_threshold", CONDITION_LESS_THAN, 95, 5, 100)
    add("lt_no_lower_exactly_equals_threshold_zero_conf", CONDITION_LESS_THAN, 100, 0, 100)
    add("lt_yes_zero_conf_strictly_below", CONDITION_LESS_THAN, 99, 0, 100)

    return {
        "description": (
            "resolve_confidence_band(condition, price_e8, conf_e8, threshold_e8). "
            "GREATER_THAN: lower>threshold -> YES(1); upper<=threshold -> NO(0); "
            "else AMBIGUOUS(null). LESS_THAN is the mirror: upper<threshold -> YES; "
            "lower>=threshold -> NO; else AMBIGUOUS. Generated by generate_fixtures.py, "
            "an independent Python re-implementation of math.rs::resolve_confidence_band."
        ),
        "cases": cases,
    }


# ---------------------------------------------------------------------------
# payout.json / refund.json — 50 heterogeneous bettors.
# ---------------------------------------------------------------------------

def build_50_stakes():
    # Heterogeneous, deterministic, no two adjacent equal: stake_i in
    # lamports, chosen so the sum does not divide evenly into the pools
    # below (forcing a non-zero floor-division remainder in both fixtures).
    stakes = []
    for i in range(50):
        stakes.append(1_000_000 + (i * 37_919) % 4_500_000 + (i % 7) * 11_003)
    return stakes


def build_payout_fixture():
    stakes = build_50_stakes()
    winning_stake = sum(stakes)
    payout_pool = 987_654_321_123  # arbitrary, deliberately not a multiple of winning_stake

    claims = [pro_rata_share(payout_pool, s, winning_stake) for s in stakes]
    total_paid = sum(claims)
    remainder = payout_pool - total_paid

    assert total_paid <= payout_pool, "I11 violated in fixture generation itself"
    assert remainder >= 0

    return {
        "description": (
            "compute_claim(payout_pool, stake_i, winning_stake) for 50 "
            "heterogeneous winning bettors, all on the winning side "
            "(winning_stake == sum(stakes)). claim_i = floor(payout_pool * "
            "stake_i / winning_stake). Checks I11: sum(claims) <= payout_pool, "
            "with the leftover remainder swept by close_event. Generated by "
            "generate_fixtures.py, an independent Python re-implementation of "
            "math.rs::compute_claim."
        ),
        "payout_pool": payout_pool,
        "winning_stake": winning_stake,
        "stakes": stakes,
        "expected_claims": claims,
        "expected_total_paid": total_paid,
        "expected_remainder_swept_by_close_event": remainder,
    }


def build_refund_fixture():
    stakes = build_50_stakes()
    pot = sum(stakes)
    resolver_reward_dev = 1_830_000  # mirrors constants::RESOLVER_REWARD_DEV
    payout_pool = pot - resolver_reward_dev  # mirrors the REFUNDABLE payout_pool formula

    refunds = [pro_rata_share(payout_pool, s, pot) for s in stakes]
    total_paid = sum(refunds)
    remainder = payout_pool - total_paid

    assert total_paid <= payout_pool, "I11 violated in fixture generation itself"
    assert remainder >= 0

    return {
        "description": (
            "compute_refund(payout_pool, stake_i, pot) for the same 50 "
            "bettors as payout.json, this time all refunded pro-rata "
            "against the whole pot regardless of outcome (the REFUNDABLE "
            "path). refund_i = floor(payout_pool * stake_i / pot), with "
            "payout_pool = pot - RESOLVER_REWARD_DEV as in "
            "finalize_resolution's AMBIGUOUS branch / mark_refundable. "
            "Checks I11: sum(refunds) <= payout_pool. Generated by "
            "generate_fixtures.py, an independent Python re-implementation "
            "of math.rs::compute_refund."
        ),
        "pot": pot,
        "resolver_reward_dev": resolver_reward_dev,
        "payout_pool": payout_pool,
        "stakes": stakes,
        "expected_refunds": refunds,
        "expected_total_paid": total_paid,
        "expected_remainder_swept_by_close_event": remainder,
    }


def main():
    fixtures = {
        "normalization.json": build_normalization_fixture(),
        "confidence_band.json": build_confidence_band_fixture(),
        "payout.json": build_payout_fixture(),
        "refund.json": build_refund_fixture(),
    }
    for filename, data in fixtures.items():
        path = os.path.join(OUT_DIR, filename)
        with open(path, "w") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
